// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// Complete state of all generated addresses
type AddressPoolAddress struct {
	ID      int32  `json:"id"`
	Site    string `json:"site"`
	Address string `json:"address"`
	// HD wallet derivation path index
	AddressIndex int32 `json:"address_index"`
	// available|reserved|used|skipped|expired
	Status       string             `json:"status"`
	Email        *string            `json:"email"`
	ReservedAt   pgtype.Timestamptz `json:"reserved_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	LastChecked  time.Time          `json:"last_checked"`
	PaymentCount *int32             `json:"payment_count"`
	// Last known balance in satoshis
	BalanceSats *int64 `json:"balance_sats"`
	// Number of transactions on-chain
	TxCount   *int32    `json:"tx_count"`
	Notes     *string   `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
}

// FIFO queue of available addresses for instant assignment
type AddressPoolQueue struct {
	Site    string    `json:"site"`
	Address string    `json:"address"`
	AddedAt time.Time `json:"added_at"`
}

// Tracks next address index for each site to prevent gaps
type AddressPoolState struct {
	Site string `json:"site"`
	// Next HD wallet index to generate
	NextIndex     int32     `json:"next_index"`
	LastUpdatedAt time.Time `json:"last_updated_at"`
	CreatedAt     time.Time `json:"created_at"`
}

// Tracks all payment transactions with complete history and status
type Payment struct {
	ID                    int32              `json:"id"`
	PaymentID             string             `json:"payment_id"`
	Address               string             `json:"address"`
	Site                  string             `json:"site"`
	TxHash                *string            `json:"tx_hash"`
	AmountBtc             pgtype.Numeric     `json:"amount_btc"`
	AmountUsd             pgtype.Numeric     `json:"amount_usd"`
	Currency              string             `json:"currency"`
	Confirmations         *int32             `json:"confirmations"`
	RequiredConfirmations *int32             `json:"required_confirmations"`
	Status                string             `json:"status"`
	Email                 *string            `json:"email"`
	OrderID               *string            `json:"order_id"`
	UserAgent             *string            `json:"user_agent"`
	IpAddress             *string            `json:"ip_address"`
	PaymentInitiatedAt    time.Time          `json:"payment_initiated_at"`
	FirstSeenAt           pgtype.Timestamptz `json:"first_seen_at"`
	ConfirmedAt           pgtype.Timestamptz `json:"confirmed_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	Notes                 *string            `json:"notes"`
	WebhookSent           *bool              `json:"webhook_sent"`
	WebhookSentAt         pgtype.Timestamptz `json:"webhook_sent_at"`
	EmailSent             *bool              `json:"email_sent"`
	EmailSentAt           pgtype.Timestamptz `json:"email_sent_at"`
	TelegramSent          *bool              `json:"telegram_sent"`
	TelegramSentAt        pgtype.Timestamptz `json:"telegram_sent_at"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	GenerationCount       *int32             `json:"generation_count"`
}
