// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	AddToQueue(ctx context.Context, arg AddToQueueParams) error
	CountAddressesByStatus(ctx context.Context, arg CountAddressesByStatusParams) (int64, error)
	// Count unique email+address combinations for pagination
	CountPaymentsGroupedByEmailAddress(ctx context.Context, arg CountPaymentsGroupedByEmailAddressParams) (int64, error)
	CountPaymentsWithFilters(ctx context.Context, arg CountPaymentsWithFiltersParams) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (AddressPoolAddress, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// Delete expired payments for a specific address (used when address is recycled)
	DeleteExpiredPaymentsByAddress(ctx context.Context, address string) error
	DeleteOldPayments(ctx context.Context, createdAt time.Time) error
	DeletePayment(ctx context.Context, paymentID string) error
	// Get currently active pending payments for monitoring
	GetActivePendingPayments(ctx context.Context) ([]GetActivePendingPaymentsRow, error)
	GetAddress(ctx context.Context, address string) (AddressPoolAddress, error)
	GetAddressByIndex(ctx context.Context, arg GetAddressByIndexParams) (AddressPoolAddress, error)
	// Get aggregated pool statistics across all sites
	GetAllPoolStats(ctx context.Context) (GetAllPoolStatsRow, error)
	// Get pool statistics grouped by site
	GetAllSitePoolStats(ctx context.Context) ([]GetAllSitePoolStatsRow, error)
	GetAvailableQueue(ctx context.Context, site string) ([]GetAvailableQueueRow, error)
	// Get average time from payment creation to confirmation
	GetAverageConfirmationTime(ctx context.Context, createdAt time.Time) (GetAverageConfirmationTimeRow, error)
	GetDailyPaymentStats(ctx context.Context, arg GetDailyPaymentStatsParams) ([]GetDailyPaymentStatsRow, error)
	// Dashboard Queries
	// Get comprehensive dashboard statistics across all sites
	GetDashboardOverview(ctx context.Context) (GetDashboardOverviewRow, error)
	GetExpiredReservations(ctx context.Context) ([]AddressPoolAddress, error)
	GetExpiredReservationsBySite(ctx context.Context, site string) ([]AddressPoolAddress, error)
	// Get hourly payment trends for the last 24 hours
	GetHourlyPaymentTrend(ctx context.Context) ([]GetHourlyPaymentTrendRow, error)
	GetPayment(ctx context.Context, paymentID string) (Payment, error)
	GetPaymentByAddress(ctx context.Context, address string) (Payment, error)
	// Calculate payment success/conversion rate
	GetPaymentConversionRate(ctx context.Context, createdAt time.Time) (GetPaymentConversionRateRow, error)
	GetPaymentCountByStatus(ctx context.Context, site string) ([]GetPaymentCountByStatusRow, error)
	GetPaymentStats(ctx context.Context, dollar_1 interface{}) (GetPaymentStatsRow, error)
	GetPaymentStatsByDateRange(ctx context.Context, arg GetPaymentStatsByDateRangeParams) (GetPaymentStatsByDateRangeRow, error)
	// Get count of payments by status for dashboard pie chart
	GetPaymentStatusDistribution(ctx context.Context) ([]GetPaymentStatusDistributionRow, error)
	GetPaymentsByDateRange(ctx context.Context, arg GetPaymentsByDateRangeParams) ([]Payment, error)
	GetPoolState(ctx context.Context, site string) (AddressPoolState, error)
	GetPoolStats(ctx context.Context, site string) (GetPoolStatsRow, error)
	// Get recent address activities showing reuse and recycling
	GetRecentAddressActivity(ctx context.Context, site string) ([]GetRecentAddressActivityRow, error)
	// Get recent completed payments only (actually paid)
	GetRecentCompletedPayments(ctx context.Context, arg GetRecentCompletedPaymentsParams) ([]GetRecentCompletedPaymentsRow, error)
	GetRecentPayments(ctx context.Context, arg GetRecentPaymentsParams) ([]Payment, error)
	// Get recent payments across all sites with pagination
	GetRecentPaymentsAllSites(ctx context.Context, arg GetRecentPaymentsAllSitesParams) ([]GetRecentPaymentsAllSitesRow, error)
	// Get statistics about address recycling for dashboard
	GetRecyclingStats(ctx context.Context, site string) (GetRecyclingStatsRow, error)
	// Get payment breakdown by site for dashboard
	GetSiteBreakdown(ctx context.Context) ([]GetSiteBreakdownRow, error)
	// Get today's statistics for dashboard summary
	GetTodayStatistics(ctx context.Context) (GetTodayStatisticsRow, error)
	// Get top paying email addresses
	GetTopPaymentEmails(ctx context.Context, limit int32) ([]GetTopPaymentEmailsRow, error)
	ListAddressesBySite(ctx context.Context, site string) ([]AddressPoolAddress, error)
	ListAddressesBySiteAndStatus(ctx context.Context, arg ListAddressesBySiteAndStatusParams) ([]AddressPoolAddress, error)
	ListExpiredPayments(ctx context.Context) ([]Payment, error)
	ListPaymentsByEmail(ctx context.Context, arg ListPaymentsByEmailParams) ([]Payment, error)
	ListPaymentsBySite(ctx context.Context, arg ListPaymentsBySiteParams) ([]Payment, error)
	ListPaymentsByStatus(ctx context.Context, arg ListPaymentsByStatusParams) ([]Payment, error)
	// Get payments grouped by email+address combination, showing only most recent with generation count
	ListPaymentsGroupedByEmailAddress(ctx context.Context, arg ListPaymentsGroupedByEmailAddressParams) ([]ListPaymentsGroupedByEmailAddressRow, error)
	ListPaymentsWithFilters(ctx context.Context, arg ListPaymentsWithFiltersParams) ([]Payment, error)
	ListPendingPayments(ctx context.Context) ([]Payment, error)
	MarkAddressUsed(ctx context.Context, address string) error
	MarkPaymentExpired(ctx context.Context, paymentID string) error
	RemoveFromQueue(ctx context.Context, arg RemoveFromQueueParams) error
	SearchPayments(ctx context.Context, arg SearchPaymentsParams) ([]Payment, error)
	UpdateAddressBalance(ctx context.Context, arg UpdateAddressBalanceParams) error
	UpdateAddressReservation(ctx context.Context, arg UpdateAddressReservationParams) error
	UpdateAddressStatus(ctx context.Context, arg UpdateAddressStatusParams) error
	UpdatePaymentCompleted(ctx context.Context, paymentID string) error
	UpdatePaymentConfirmed(ctx context.Context, arg UpdatePaymentConfirmedParams) error
	UpdatePaymentEmailSent(ctx context.Context, paymentID string) error
	UpdatePaymentTelegramSent(ctx context.Context, paymentID string) error
	UpdatePaymentTransaction(ctx context.Context, arg UpdatePaymentTransactionParams) error
	UpdatePaymentWebhookSent(ctx context.Context, paymentID string) error
	UpsertPoolState(ctx context.Context, arg UpsertPoolStateParams) error
}

var _ Querier = (*Queries)(nil)
