name: Deploy Go App to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Debug - List repository structure
        run: |
          # Replace this path with your actual main.go location
          # For example, if main.go is at the root:
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ${{ secrets.APP_NAME }} .
          
          echo "Build complete: ${{ secrets.APP_NAME }}"

      - name: Build Go Application
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ${{ secrets.APP_NAME }} ./cmd/server/main.go
          echo "Build complete: ${{ secrets.APP_NAME }}"

      - name: Run Tests
        run: go test ./...

      - name: Prepare Artifact
        run: |
          tar -czf artifact.tar.gz ${{ secrets.APP_NAME }}
          echo "Artifact created: artifact.tar.gz"

      - name: Upload to VPS and Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          port: ${{ secrets.VPS_SSH_PORT }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "artifact.tar.gz"
          target: "/home/${{ secrets.VPS_SSH_USER }}/uploads"

      - name: Execute Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          port: ${{ secrets.VPS_SSH_PORT }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            TIMESTAMP=$(date +%s)
            ARTIFACT_PATH="/home/${{ secrets.VPS_SSH_USER }}/uploads/artifact.tar.gz"
            RENAMED_PATH="/opt/deploy/artifacts/${{ secrets.APP_NAME }}_${TIMESTAMP}.tar.gz"
            sudo mkdir -p /opt/deploy/artifacts
            sudo cp $ARTIFACT_PATH $RENAMED_PATH
            sudo chown perigrine:perigrine $RENAMED_PATH
            sudo /opt/deploy/scripts/deploy.sh ${{ secrets.APP_NAME }} $RENAMED_PATH
            rm $ARTIFACT_PATH